"""
Door generator.

Generates door properties (size, style, etc.) for placed doors.
The FloorGenerator handles placement, this handles properties.
"""

from typing import Any, Dict
from core.generator_base import GeneratorBase
from core.footprint import Point2D
import random


class DoorProperties:
    """
    Properties for a door (size, style, etc.).
    
    This is generated by DoorGenerator and combined with placement info
    to create the final door representation.
    """
    
    def __init__(
        self,
        width: float = 0.8,
        height: float = 2.5,
        style: str = "standard",
        is_main_entrance: bool = False
    ):
        """
        Initialize door properties.
        
        Args:
            width: Door width in meters
            height: Door height in meters
            style: Door style (standard, double, sliding, etc.)
            is_main_entrance: Whether this is the main building entrance
        """
        self.width = width
        self.height = height
        self.style = style
        self.is_main_entrance = is_main_entrance


class DoorGenerator(GeneratorBase):
    """
    Generates door properties based on context and parameters.
    
    Note: This does NOT handle placement - that's the FloorGenerator's job.
    This only determines door size, style, and other properties.
    """
    
    def generate(
        self,
        parent_context: Any,  # Could be placement info, building style, etc.
        seed: int,
        door_idx: int = 0,
        total_doors: int = 1,
        **params: Dict[str, Any]
    ) -> DoorProperties:
        """
        Generate properties for a door.
        
        Args:
            parent_context: Context information (floor, building style, etc.)
            seed: Generation seed
            door_idx: Index of this door (0 = first door, useful for main entrance)
            total_doors: Total number of doors on this floor
            **params: Override parameters (width, height, style, etc.)
            
        Returns:
            DoorProperties object
        """
        rng = random.Random(seed)
        
        # Extract only the relevant door parameters
        door_params = {}
        if 'width' in params:
            door_params['width'] = params['width']
        if 'height' in params:
            door_params['height'] = params['height']
        if 'style' in params:
            door_params['style'] = params['style']
        
        # First door is main entrance
        door_params['is_main_entrance'] = (door_idx == 0)
        
        # Special case: wider main entrance (if not explicitly set)
        if door_params['is_main_entrance'] and 'width' not in door_params:
            door_params['width'] = 1.0  # Slightly wider for main entrance
        
        # Let DoorProperties handle all other defaults
        return DoorProperties(**door_params)
