"""
Window generator.

Generates window properties (size, style, etc.) for placed windows.
The FloorGenerator handles placement, this handles properties.
"""

from typing import Any, Dict
from core.generator_base import GeneratorBase
from core.footprint import Point2D
import random


class WindowProperties:
    """
    Properties for a window (size, elevation, style, etc.).
    
    This is generated by WindowGenerator and combined with placement info
    to create the final window representation.
    """
    
    def __init__(
        self,
        width: float = 0.6,
        height: float = 1.2,
        elevation: float = 0.9,  # Height from floor to window bottom
        style: str = "standard"
    ):
        """
        Initialize window properties.
        
        Args:
            width: Window width in meters
            height: Window height in meters
            elevation: Height from floor to window sill in meters
            style: Window style (standard, large, narrow, etc.)
        """
        self.width = width
        self.height = height
        self.elevation = elevation
        self.style = style


class WindowGenerator(GeneratorBase):
    """
    Generates window properties based on context and parameters.
    
    Note: This does NOT handle placement - that's the FloorGenerator's job.
    This only determines window size, elevation, style, and other properties.
    """
    
    def generate(
        self,
        parent_context: Any,  # Floor object
        seed: int,
        window_idx: int = 0,
        total_windows: int = 1,
        floor_idx: int = 0,
        **params: Dict[str, Any]
    ) -> WindowProperties:
        """
        Generate properties for a window.
        
        Args:
            parent_context: Context information (floor, building style, etc.)
            seed: Generation seed
            window_idx: Index of this window
            total_windows: Total number of windows on this floor
            floor_idx: Floor index
            **params: Override parameters (width, height, elevation, style, etc.)
            
        Returns:
            WindowProperties object
        """
        rng = random.Random(seed)
        
        # Extract only the relevant window parameters
        window_params = {}
        if 'width' in params:
            window_params['width'] = params['width']
        if 'height' in params:
            window_params['height'] = params['height']
        if 'elevation' in params:
            window_params['elevation'] = params['elevation']
        if 'style' in params:
            window_params['style'] = params['style']
        
        # Special case: larger windows on ground floor (if not explicitly set)
        if floor_idx == 0 and 'height' not in window_params:
            window_params['height'] = 1.6  # Slightly taller on ground floor
        
        # Let WindowProperties handle all defaults
        return WindowProperties(**window_params)
