"""
Door generator and Door class.

Contains:
- Door class: complete door representation (placement + properties)
- DoorProperties: door properties (size, style, etc.)
- DoorGenerator: generates door properties for placed doors

The FloorGenerator handles placement logic, this handles the Door class and its properties.
"""

from typing import Any, Dict, Tuple
from core.generator_base import GeneratorBase
from core.footprint import Point2D
import random


class Door:
    """
    Complete door representation: placement + properties.
    
    Created by FloorGenerator by combining placement logic with 
    properties from DoorGenerator.
    """
    
    def __init__(
        self,
        edge_idx: int,
        position_on_edge: float,
        edge_start: Point2D,
        edge_end: Point2D,
        facing_direction: Tuple[float, float],
        floor_idx: int,
        properties: 'DoorProperties'
    ):
        """
        Initialize door.
        
        Args:
            edge_idx: Index of the edge this door is on
            position_on_edge: Position along edge (0.0 = start, 1.0 = end)
            edge_start: Start point of the edge
            edge_end: End point of the edge
            facing_direction: Normalized direction the door faces (outward normal)
            floor_idx: Floor index
            properties: Door properties (size, style, etc.)
        """
        self.edge_idx = edge_idx
        self.position_on_edge = position_on_edge
        self.edge_start = edge_start
        self.edge_end = edge_end
        self.facing_direction = facing_direction
        self.floor_idx = floor_idx
        self.properties = properties
    
    def get_world_position(self) -> Point2D:
        """Calculate actual world (x, y) position of door center."""
        x = self.edge_start[0] + (self.edge_end[0] - self.edge_start[0]) * self.position_on_edge
        y = self.edge_start[1] + (self.edge_end[1] - self.edge_start[1]) * self.position_on_edge
        return (x, y)
    
    @property
    def width(self) -> float:
        """Door width."""
        return self.properties.width
    
    @property
    def height(self) -> float:
        """Door height."""
        return self.properties.height
    
    @property
    def is_main_entrance(self) -> bool:
        """Whether this is the main entrance."""
        return self.properties.is_main_entrance


class DoorProperties:
    """
    Properties for a door (size, style, etc.).
    
    This is generated by DoorGenerator and combined with placement info
    to create the final door representation.
    """
    
    def __init__(
        self,
        width: float = 0.8,
        height: float = 2.5,
        style: str = "standard",
        is_main_entrance: bool = False
    ):
        """
        Initialize door properties.
        
        Args:
            width: Door width in meters
            height: Door height in meters
            style: Door style (standard, double, sliding, etc.)
            is_main_entrance: Whether this is the main building entrance
        """
        self.width = width
        self.height = height
        self.style = style
        self.is_main_entrance = is_main_entrance


class DoorGenerator(GeneratorBase):
    """
    Generates door properties based on context and parameters.
    
    Note: This does NOT handle placement - that's the FloorGenerator's job.
    This only determines door size, style, and other properties.
    """
    
    def generate(
        self,
        parent_context: Any,  # Could be placement info, building style, etc.
        seed: int,
        door_idx: int = 0,
        total_doors: int = 1,
        **params: Dict[str, Any]
    ) -> DoorProperties:
        """
        Generate properties for a door.
        
        Args:
            parent_context: Context information (floor, building style, etc.)
            seed: Generation seed
            door_idx: Index of this door (0 = first door, useful for main entrance)
            total_doors: Total number of doors on this floor
            **params: Override parameters (width, height, style, etc.)
            
        Returns:
            DoorProperties object
        """
        rng = random.Random(seed)
        
        # Extract only the relevant door parameters
        door_params = {}
        if 'width' in params:
            door_params['width'] = params['width']
        if 'height' in params:
            door_params['height'] = params['height']
        if 'style' in params:
            door_params['style'] = params['style']
        
        # First door is main entrance
        door_params['is_main_entrance'] = (door_idx == 0)
        
        # Special case: wider main entrance (if not explicitly set)
        if door_params['is_main_entrance'] and 'width' not in door_params:
            door_params['width'] = 1.0  # Slightly wider for main entrance
        
        # Let DoorProperties handle all other defaults
        return DoorProperties(**door_params)
