"""
Window generator and Window class.

Contains:
- Window class: complete window representation (placement + properties)
- WindowProperties: window properties (size, style, etc.)
- WindowGenerator: generates window properties for placed windows

The FloorGenerator handles placement logic, this handles the Window class and its properties.
"""

from typing import Any, Dict, Tuple
from core.generator_base import GeneratorBase
from core.footprint import Point2D
import random


class Window:
    """
    Complete window representation: placement + properties.
    
    Created by FloorGenerator by combining placement logic with
    properties from WindowGenerator.
    """
    
    def __init__(
        self,
        edge_idx: int,
        position_on_edge: float,
        edge_start: Point2D,
        edge_end: Point2D,
        facing_direction: Tuple[float, float],
        floor_idx: int,
        properties: 'WindowProperties'
    ):
        """
        Initialize window.
        
        Args:
            edge_idx: Index of the edge this window is on
            position_on_edge: Position along edge (0.0 = start, 1.0 = end)
            edge_start: Start point of the edge
            edge_end: End point of the edge
            facing_direction: Normalized direction the window faces (outward normal)
            floor_idx: Floor index
            properties: Window properties (size, elevation, style, etc.)
        """
        self.edge_idx = edge_idx
        self.position_on_edge = position_on_edge
        self.edge_start = edge_start
        self.edge_end = edge_end
        self.facing_direction = facing_direction
        self.floor_idx = floor_idx
        self.properties = properties
    
    def get_world_position(self) -> Point2D:
        """Calculate actual world (x, y) position of window center."""
        x = self.edge_start[0] + (self.edge_end[0] - self.edge_start[0]) * self.position_on_edge
        y = self.edge_start[1] + (self.edge_end[1] - self.edge_start[1]) * self.position_on_edge
        return (x, y)
    
    @property
    def width(self) -> float:
        """Window width."""
        return self.properties.width
    
    @property
    def height(self) -> float:
        """Window height."""
        return self.properties.height
    
    @property
    def elevation(self) -> float:
        """Window elevation (height from floor to window sill)."""
        return self.properties.elevation


class WindowProperties:
    """
    Properties for a window (size, elevation, style, etc.).
    
    This is generated by WindowGenerator and combined with placement info
    to create the final window representation.
    """
    
    def __init__(
        self,
        width: float = 0.6,
        height: float = 1.2,
        elevation: float = 0.9,  # Height from floor to window bottom
        style: str = "standard"
    ):
        """
        Initialize window properties.
        
        Args:
            width: Window width in meters
            height: Window height in meters
            elevation: Height from floor to window sill in meters
            style: Window style (standard, large, narrow, etc.)
        """
        self.width = width
        self.height = height
        self.elevation = elevation
        self.style = style


class WindowGenerator(GeneratorBase):
    """
    Generates window properties based on context and parameters.
    
    Note: This does NOT handle placement - that's the FloorGenerator's job.
    This only determines window size, elevation, style, and other properties.
    """
    
    def generate(
        self,
        parent_context: Any,  # Floor object
        seed: int,
        window_idx: int = 0,
        total_windows: int = 1,
        floor_idx: int = 0,
        **params: Dict[str, Any]
    ) -> WindowProperties:
        """
        Generate properties for a window.
        
        Args:
            parent_context: Context information (floor, building style, etc.)
            seed: Generation seed
            window_idx: Index of this window
            total_windows: Total number of windows on this floor
            floor_idx: Floor index
            **params: Override parameters (width, height, elevation, style, etc.)
            
        Returns:
            WindowProperties object
        """
        rng = random.Random(seed)
        
        # Extract only the relevant window parameters
        window_params = {}
        if 'width' in params:
            window_params['width'] = params['width']
        if 'height' in params:
            window_params['height'] = params['height']
        if 'elevation' in params:
            window_params['elevation'] = params['elevation']
        if 'style' in params:
            window_params['style'] = params['style']
        
        # Special case: larger windows on ground floor (if not explicitly set)
        if floor_idx == 0 and 'height' not in window_params:
            window_params['height'] = 1.6  # Slightly taller on ground floor
        
        # Let WindowProperties handle all defaults
        return WindowProperties(**window_params)
